config/routes.rb
TodoList::Application.routes.draw do
  devise_for :users
  root to: 'home#index'

  resources :projects do
    member do
      get :add_task
    end

    resources :tasks, only: [:create, :update]
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    unless user.guest?
      can :manage, Project, user_id: user.id
      can :manage, Task do |task|
        task.project.user == user
      end
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user

  has_many :tasks

  validates :name, presence: true
  validates :user, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project

  validates :description, presence: true
  validates :project,     presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :projects

  def guest?
    self.new_record?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |user| user.permit(:email, :password, :remember_me) }

    devise_parameter_sanitizer.for(:sign_up) do |user|
      user.permit(:email, :password, :password_confirmation)
    end
  end
end

app/controllers/authorized_controller.rb
class AuthorizedController < ApplicationController
  before_filter :authenticate_user!
  check_authorization
  load_and_authorize_resource
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/projects_controller.rb
class ProjectsController < AuthorizedController
  before_filter :populate_projects, only: [:edit, :new, :show]

  prepend_before_filter do
    params[:project] &&= project_params
  end

  def show
  end

  def edit
  end

  def new
  end

  def update
  end

  def create
    if @project.save
      redirect_to project_path(@project), notice: t('strings.success')
    else
      flash.now[:error] = t('strings.error')
      render :new
    end
  end

  def add_task
    @task = @project.tasks.build
  end

  protected

  def populate_projects
    @projects = current_user.projects
  end

  def project_params
    params.require(:project).permit(:name)#, entries_attributes: [:id, :resource_type, :resource_id, :_destroy])
  end
end

app/controllers/tasks_controller.rb
class TasksController < AuthorizedController

  prepend_before_filter do
    params[:task] &&= task_params
  end

  def create
    @task.save
  end

  def update
    @task.update_attributes(task_params)
  end

  protected

  def task_params
    finished = params[:task].delete(:finished_at)
    if finished
      params[:task].merge!(finished_at: Date.today)
    else
      params[:task].merge!(finished_at: nil)
    end
    params.require(:task).permit(:description, :finished_at, :project_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    flash.collect do |key, msg|
      content_tag :div, class: "message #{key}" do
        content_tag(:p, msg)
      end
    end.join.html_safe
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.haml
Home

app/views/layouts/application.html.haml
!!! 5
-# paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7]    <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8]    <html class="no-js lt-ie9" lang="en">
/[if gt IE 8] <!--> <html class="no-js" lang="en"> <!--

%head
  %title Todo List

  %meta{ name: 'description', content: '' }
  %meta{ name: 'keywords', content: '' }
  %meta{ charset: 'utf-8'}
  %meta{ name: 'viewport', content: 'width=device-width,initial-scale=1' }
  -# Use the .htaccess and remove these lines to avoid edge case issues.  More info: h5bp.com/b/378
  %meta{ 'http-equiv' => 'X-UA-Compatible', content: 'IE=edge,chrome=1' }

  = javascript_include_tag 'modernizr.custom.js'

  %link{ href: '//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css', rel: 'stylesheet' }
  = stylesheet_link_tag :application
  %link{ rel: "shortcut icon", href: "/favicon.ico", type: "image/x-icon" }
  %link{ rel: "icon", href: "/favicon.ico", type: "image/x-icon" }

  = csrf_meta_tag

%body
  <!--[if lt IE 7]>
  <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
  <![endif]-->

  = flash_messages

  .nav
    .nav-wrapper
      .menu
        %ul
          %li= link_to t('links.home'), root_path
          - if user_signed_in?
            %li= link_to t('links.my_projects'), projects_path

      .extra
        - if user_signed_in?
          %span.username= current_user.email
          |
          = link_to t('links.logout'), destroy_user_session_path, method: :delete
        - else
          = link_to t('links.login'), new_user_session_path
          |
          = link_to t('links.signup'), new_user_registration_path

  %article
    .content= yield

  .clear
  %footer

  = javascript_include_tag :application
  = yield :javascript

app/views/projects/_form.html.haml
= form_for @project do |f|
  .field
    = f.label :name
    = f.text_field :name
  .submit
    = f.submit t('strings.confirm')
    = link_to t('links.back'), projects_path

app/views/projects/_side.html.haml
%ul.my_projects
  %li= link_to t('links.new_project'), new_project_path
  - projects.each do |project|
    %li= link_to project.name, project_path(project)

app/views/projects/add_task.js.erb
$('.task-list').prepend('<%= j render @task %>')

app/views/projects/edit.html.haml
%h1= "Editar projeto: #{@project.name}"
= render 'form', project: @project

app/views/projects/index.html.haml
%h1 Meus Projetos
= render 'side', projects: @projects
.project= t('strings.select_a_project_or_create_one')

app/views/projects/new.html.haml
%h1 Novo Projeto
= render 'form', project: @project

app/views/projects/show.html.haml
%h1= "Projeto #{@project.name}"

= render 'side', projects: @projects

.project
  = link_to t('links.add_task'), add_task_project_path(@project), remote: true
  .task-list
  - if @project.tasks.blank?
    = t('strings.project_with_no_tasks')
  - else
    = render @project.tasks

app/views/tasks/_task.html.haml
- if task.finished_at
  %p.done= task.description
- else
  - form_id = "task_form_#{task.object_id}"
  = form_for [task.project, task], remote: true, html: { id: form_id } do |f|
    = f.hidden_field :project_id, value: task.project.id
    = f.check_box :finished_at, onchange: "$('##{form_id}').trigger('submit')"
    - if task.new_record?
      = f.text_field :description, onblur: "$('##{form_id}').trigger('submit')"
    - else
      %span= task.description

app/views/tasks/create.js.erb
<%- if @task.id %>
  alert('Tarefa salva com sucesso')
<% end %>

app/views/tasks/update.js.erb
<%- if @task.valid? %>
  alert('Tarefa atualizada com sucesso.')
<% end %>